### ISSUE TITLE
What is the license which applies to this repository?

### ISSUE THREAD

**Issue by ifraixedes** [mattrobenolt/email-me#3]
Hi Matt,

Thanks for this work, however could you add a license to the repository or make it clear if it already has one to know the implications of using it?

Thanks.

**Comment by mattrobenolt** [comment]
Oh, oops, I swore I added a LICENSE file. Fixing. :)

**Comment by mattrobenolt** [comment]
@ifraixedes There, it's a 3-clause BSD.

**Comment by ifraixedes** [comment]
Ok, thanks, that has been so quick.
